import * as day1 from "./day1/main.ts";
import * as day2 from "./day2/main.ts";
import * as day3 from "./day3/main.ts";
import * as day4 from "./day4/main.ts";
import * as day5 from "./day5/main.ts";

console.log("\n");
console.log(" DAY | PART | RESULT");
console.log(" --- | ---- | ------");
console.log(` 1   | 1    | ${day1.part1()}`);
console.log(`     | 2    | ${day1.part2()}`);
console.log(" --- | ---- | ------");
console.log(` 2   | 1    | ${day2.part1()}`);
console.log(`     | 2    | ${day2.part2()}`);
console.log(" --- | ---- | ------");
console.log(` 3   | 1    | ${day3.partOne()}`);
console.log(`     | 2    | ${day3.partTwo()}`);
console.log(" --- | ---- | ------");
console.log(` 4   | 1    | ${day4.partOne()}`);
console.log(`     | 2    | ${day4.partTwo()}`);
console.log(" --- | ---- | ------");
console.log(` 5   | 1    | ${day5.partOne()}`);
console.log(`     | 2    | ${day5.partTwo()}`);
